name: action

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
  steps:
  - uses: actions/checkout@main
  - uses: nanasess/setup-php@main
    with:
      php-version: '5.6'
  - run: php index.php