name: action

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04

steps:
- uses: actions/checkout@master
- uses: nanasess/setup-php@master
  with:
    php-version: '5.6'
- run: php index.php