on:
  workflow_dispatch
  #push:
  #  branches:
  #    - '*'
  #pull_request:
  #  branches:
  #    - 'main'
  #  types: [closed]

name: Metric analyses on EC2

jobs:
  metrics:
    runs-on: [self-hosted, Windows, X64, Windows-on-aws]
    steps:
    - name: Metrics
      uses: actions/checkout@main
    - env:
        UNDERSTAND_LICENSE: ${{ secrets.UNDERSTAND_LICENSE }}
      run:  |
        #Pathを追加
        $ENV:Path+="C:\Program Files\SciTools\bin\pc-win64\;"
        $ENV:Path.Split(";")
    #    # ライセンス認証
    #    und -setlicensecode "$env:UNDERSTAND_LICENSE"
    #    # undコマンドに入る
    #    und
    #    # & 'C:\Program Files\SciTools\bin\pc-win64\und.exe'
    #    # メトリクスを出力する
    #    metrics -db c:\understand\work\peco.udb
    #    # undコマンドを終了する
    #    exit
    #- name: Metrics
    #  run:  |
    #    # pathを出力
    #    $ENV:Path.Split(";")
    #    # understandバッチを実行する
    #    C:\understand\workK\batch\AnalyzeSimple.bat

    - name: Archive metrics results
      uses: actions/upload-artifact@v2
      with:
        name: metrics-report
        path: C:\understand\work\peco.csv