on:
  workflow_dispatch
  #push:
  #  branches:
  #    - '*'
  #pull_request:
  #  branches:
  #    - 'main'
  #  types: [closed]

name: Metric analyses on EC2

jobs:
  metrics:
    runs-on: [self-hosted, Windows, X64, Windows-on-aws]
    steps:
    - name: Set License
      uses: actions/checkout@main
    - name:
    - env:
        UNDERSTAND_LICENSE: ${{ secrets.UNDERSTAND_LICENSE }}
      run:  |
        # Pathを追加
        $ENV:Path+=";C:\Program Files\SciTools\bin\pc-win64\;"
        # Pathの確認
        $ENV:Path.Split(";")
        # undコマンドが通ってることを確認
        Get-Command und
        # レポート出力先フォルダ内を確認
        Get-ChildItem C:\understand\workK\udbSimple\
        # レポート出力先フォルダ内のファイルを削除
        Get-ChildItem C:\understand\workK\udbSimple\ -Include *.* -Recurse | del
        # レポート出力先フォルダ内を確認
        Get-ChildItem C:\understand\workK\udbSimple\
        # ライセンス認証
        und -setlicensecode "$env:UNDERSTAND_LICENSE"
    - name: Metrics
      run:  |
        # understandバッチを実行する
        C:\understand\workK\batch\AnalyzeSimple.bat

    - name: Archive metrics results
      uses: actions/upload-artifact@v2
      with:
        name: metrics-report
        path: |
          C:\understand\workK\udbSimple\school-web-simple.csv
          C:\understand\workK\udbSimple\DataDictionary.txt